name: Build and Push Docker Image

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Debug files
      run: ls -R

    - name: Show Dockerfile location
      run: find . -name Dockerfile

    - name: Build image
      run: docker build -f ./devops-demo/Dockerfile -t ghcr.io/${{ secrets.GHCR_USERNAME }}/devops-demo:latest .

    - name: Push image
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/devops-demo:latest
